name: Dry Run

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create and checkout release branch
        run: |
          git config --global user.email "opensource-svc@intuit.com"
          git config --global user.name "intuit-svc"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npx pnpm@8 i

      - name: Build Project
        run: npx bazel build //...

      - name: Dry Run
        run: npx auto shipit --dry-run
        with:
          github-token: ${{ secrets.GH_TOKEN }}
